import csv
import html
import io
import textwrap
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from xml.sax.saxutils import escape as xml_escape


DEFAULT_POINTS = [
    "Define the objective and audience.",
    "Summarize the relevant data or context.",
    "Present the key findings clearly.",
    "Recommend practical next steps.",
]


def clean_title(title):
    title = " ".join((title or "").split())
    return title or "DataBot Analysis"


def parse_points(text):
    points = []
    for raw_line in (text or "").splitlines():
        point = raw_line.strip().lstrip("-*0123456789. )\t")
        if point:
            points.append(point)
    return points or DEFAULT_POINTS


def parse_csv_bytes(file_bytes):
    if not file_bytes:
        return [], []

    text = None
    for encoding in ("utf-8-sig", "utf-8", "latin-1"):
        try:
            text = file_bytes.decode(encoding)
            break
        except UnicodeDecodeError:
            continue

    if text is None:
        return [], []

    reader = csv.DictReader(io.StringIO(text))
    rows = list(reader)
    return reader.fieldnames or [], rows


def infer_chart_data(columns, rows, max_points=10):
    if not columns or not rows:
        return ["Planning", "Analysis", "Output", "Review"], [25, 55, 80, 65]

    numeric_column = None
    for column in columns:
        numeric_values = []
        for row in rows[:50]:
            value = str(row.get(column, "")).replace(",", "").strip()
            if not value:
                continue
            try:
                numeric_values.append(float(value))
            except ValueError:
                pass
        if numeric_values:
            numeric_column = column
            break

    if numeric_column is None:
        return ["Rows", "Columns", "Fields"], [len(rows), len(columns), max(len(columns) - 1, 1)]

    label_column = next((column for column in columns if column != numeric_column), numeric_column)
    labels = []
    values = []
    for index, row in enumerate(rows):
        if len(values) >= max_points:
            break
        raw_value = str(row.get(numeric_column, "")).replace(",", "").strip()
        try:
            value = float(raw_value)
        except ValueError:
            continue
        label = str(row.get(label_column, "")).strip() or f"Row {index + 1}"
        labels.append(label[:24])
        values.append(value)

    return labels or ["No numeric values"], values or [0]


def _svg_text(text, x, y, size=14, weight="400", color="#15211d", anchor="start"):
    return (
        f'<text x="{x}" y="{y}" font-family="Arial, sans-serif" '
        f'font-size="{size}" font-weight="{weight}" fill="{color}" text-anchor="{anchor}">'
        f"{html.escape(str(text))}</text>"
    )


def build_chart_svg(title, labels, values):
    title = clean_title(title)
    labels = labels or ["No data"]
    values = values or [0]
    width, height = 960, 540
    left, top, chart_width, chart_height = 90, 92, 800, 330
    max_value = max(max(values), 1)
    bar_gap = 18
    bar_width = max(24, (chart_width - bar_gap * (len(values) - 1)) / max(len(values), 1))

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="960" height="540" fill="#f7f8f5"/>',
        '<rect x="42" y="38" width="876" height="454" rx="8" fill="#ffffff" stroke="#dfe5e1"/>',
        _svg_text(title, 70, 76, 24, "700"),
        _svg_text("Generated by DataBot", 890, 76, 13, "600", "#5e6b66", "end"),
        f'<line x1="{left}" y1="{top + chart_height}" x2="{left + chart_width}" y2="{top + chart_height}" stroke="#9da9a4"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + chart_height}" stroke="#9da9a4"/>',
    ]

    for index, value in enumerate(values):
        bar_height = 0 if max_value == 0 else (value / max_value) * (chart_height - 24)
        x = left + index * (bar_width + bar_gap)
        y = top + chart_height - bar_height
        parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_width:.1f}" height="{bar_height:.1f}" rx="4" fill="#176b4d"/>')
        parts.append(_svg_text(f"{value:g}", x + bar_width / 2, y - 10, 13, "700", "#176b4d", "middle"))
        wrapped_label = textwrap.shorten(str(labels[index]), width=16, placeholder="...")
        parts.append(_svg_text(wrapped_label, x + bar_width / 2, top + chart_height + 28, 12, "600", "#5e6b66", "middle"))

    parts.append("</svg>")
    return "\n".join(parts).encode("utf-8")


def build_diagram_svg(title, points):
    title = clean_title(title)
    points = parse_points("\n".join(points))[:5]
    width, height = 960, 540
    card_width, card_height = 250, 92
    start_x, start_y = 70, 145
    gap_x, gap_y = 70, 74

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="960" height="540" fill="#f7f8f5"/>',
        _svg_text(title, 70, 76, 25, "700"),
        _svg_text("Decision flow", 70, 104, 14, "700", "#d89a32"),
        '<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#176b4d"/></marker></defs>',
    ]

    positions = []
    for index, point in enumerate(points):
        row = index // 3
        col = index % 3
        x = start_x + col * (card_width + gap_x)
        y = start_y + row * (card_height + gap_y)
        positions.append((x, y))
        parts.append(f'<rect x="{x}" y="{y}" width="{card_width}" height="{card_height}" rx="8" fill="#ffffff" stroke="#dfe5e1"/>')
        parts.append(_svg_text(f"Step {index + 1}", x + 18, y + 27, 12, "700", "#176b4d"))
        wrapped = textwrap.wrap(point, width=30)[:3]
        for line_index, line in enumerate(wrapped):
            parts.append(_svg_text(line, x + 18, y + 53 + line_index * 18, 14, "600"))

    for index in range(len(positions) - 1):
        x1, y1 = positions[index]
        x2, y2 = positions[index + 1]
        if y1 == y2:
            parts.append(f'<line x1="{x1 + card_width}" y1="{y1 + card_height / 2}" x2="{x2 - 14}" y2="{y2 + card_height / 2}" stroke="#176b4d" stroke-width="3" marker-end="url(#arrow)"/>')
        else:
            parts.append(f'<path d="M{x1 + card_width / 2},{y1 + card_height} C{x1 + card_width / 2},{y1 + card_height + 50} {x2 + card_width / 2},{y2 - 50} {x2 + card_width / 2},{y2 - 14}" fill="none" stroke="#176b4d" stroke-width="3" marker-end="url(#arrow)"/>')

    parts.append("</svg>")
    return "\n".join(parts).encode("utf-8")


def _pdf_escape(text):
    return str(text).replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_pdf_report(title, brief, points):
    title = clean_title(title)
    points = parse_points("\n".join(points))
    lines = [title, "", "Prepared by DataBot", datetime.now(UTC).strftime("%Y-%m-%d"), ""]
    if brief:
        lines.extend(textwrap.wrap("Brief: " + brief, width=88))
        lines.append("")
    lines.append("Key Points")
    for index, point in enumerate(points, 1):
        lines.extend(textwrap.wrap(f"{index}. {point}", width=88))
    lines.extend(["", "Recommended Next Steps"])
    lines.extend(
        [
            "1. Validate the assumptions with the target audience.",
            "2. Review source data quality before making decisions.",
            "3. Convert the strongest findings into measurable actions.",
        ]
    )

    content_lines = ["BT", "/F1 18 Tf", "72 760 Td", f"({_pdf_escape(lines[0])}) Tj"]
    content_lines.extend(["/F1 10 Tf", "0 -28 Td"])
    for line in lines[2:]:
        content_lines.append(f"({_pdf_escape(line)}) Tj")
        content_lines.append("0 -15 Td")
    content_lines.append("ET")
    stream = "\n".join(content_lines).encode("latin-1", errors="replace")

    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    output = io.BytesIO()
    output.write(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, 1):
        offsets.append(output.tell())
        output.write(f"{index} 0 obj\n".encode("ascii"))
        output.write(obj)
        output.write(b"\nendobj\n")
    xref = output.tell()
    output.write(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    output.write(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        output.write(f"{offset:010d} 00000 n \n".encode("ascii"))
    output.write(
        f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode("ascii")
    )
    return output.getvalue()


def _slide_xml(title, bullets):
    bullet_xml = ""
    for index, bullet in enumerate(bullets[:7]):
        y = 170 + index * 58
        bullet_xml += (
            f'<p:sp><p:nvSpPr><p:cNvPr id="{index + 10}" name="Bullet {index + 1}"/>'
            '<p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr>'
            f'<a:xfrm><a:off x="914400" y="{y * 9525}"/><a:ext cx="7315200" cy="457200"/></a:xfrm>'
            '</p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="2200"/>'
            f'<a:t>{xml_escape(bullet)}</a:t></a:r></a:p></p:txBody></p:sp>'
        )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="F7F8F5"/></a:solidFill></p:bgPr></p:bg>
    <p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
      <p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="685800" y="457200"/><a:ext cx="7772400" cy="762000"/></a:xfrm></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="3400" b="1"><a:solidFill><a:srgbClr val="15211D"/></a:solidFill></a:rPr><a:t>{xml_escape(title)}</a:t></a:r></a:p></p:txBody></p:sp>
      {bullet_xml}
    </p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>'''


def build_powerpoint(title, brief, points):
    title = clean_title(title)
    points = parse_points("\n".join(points))
    slides = [
        (title, [brief or "Professional artifact generated by DataBot.", "Prepared for review and decision-making."]),
        ("Key Findings", points[:5]),
        ("Recommended Next Steps", [
            "Validate assumptions and data sources.",
            "Prioritize the highest-impact action.",
            "Define owners, deadlines, and success metrics.",
        ]),
    ]
    output = io.BytesIO()
    with zipfile.ZipFile(output, "w", zipfile.ZIP_DEFLATED) as pptx:
        pptx.writestr("[Content_Types].xml", _content_types(len(slides)))
        pptx.writestr("_rels/.rels", _root_rels())
        pptx.writestr("ppt/presentation.xml", _presentation_xml(len(slides)))
        pptx.writestr("ppt/_rels/presentation.xml.rels", _presentation_rels(len(slides)))
        for index, (slide_title, bullets) in enumerate(slides, 1):
            pptx.writestr(f"ppt/slides/slide{index}.xml", _slide_xml(slide_title, bullets))
            pptx.writestr(f"ppt/slides/_rels/slide{index}.xml.rels", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>')
    return output.getvalue()


def _content_types(slide_count):
    overrides = "\n".join(
        f'<Override PartName="/ppt/slides/slide{index}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
        for index in range(1, slide_count + 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  {overrides}
</Types>'''


def _root_rels():
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>'''


def _presentation_rels(slide_count):
    rels = "\n".join(
        f'<Relationship Id="rId{index}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{index}.xml"/>'
        for index in range(1, slide_count + 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  {rels}
</Relationships>'''


def _presentation_xml(slide_count):
    slide_ids = "\n".join(
        f'<p:sldId id="{255 + index}" r:id="rId{index}"/>'
        for index in range(1, slide_count + 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:sldIdLst>{slide_ids}</p:sldIdLst>
  <p:sldSz cx="9144000" cy="5143500" type="screen16x9"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>'''


def safe_filename(title, suffix):
    stem = "".join(char.lower() if char.isalnum() else "-" for char in clean_title(title))
    stem = "-".join(part for part in stem.split("-") if part)[:64] or "databot-artifact"
    return f"{stem}.{suffix.lstrip('.')}"


def generate_artifacts(title, brief, points_text, csv_file_bytes=None):
    points = parse_points(points_text)
    columns, rows = parse_csv_bytes(csv_file_bytes)
    labels, values = infer_chart_data(columns, rows)
    chart_title = f"{clean_title(title)} Chart"
    diagram_title = f"{clean_title(title)} Workflow"
    return {
        "pdf": build_pdf_report(title, brief, points),
        "chart_svg": build_chart_svg(chart_title, labels, values),
        "diagram_svg": build_diagram_svg(diagram_title, points),
        "pptx": build_powerpoint(title, brief, points),
    }
